name: Auto Update Code from Issue

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  update-code:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai

      # Run Python script
      - name: Run Python script to update code
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "${{ github.event.issue.body }}" > issue_body.txt
          python update_code.py "${{ github.event.issue.title }}" issue_body.txt

      # Commit and push
      - name: Commit & push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="issue-fix-${{ github.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          git add store.py
          git commit -m "Automated fix for issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push -u origin $BRANCH_NAME

      # Create pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          branch: issue-fix-${{ github.event.issue.number }}
          base: main
          title: "Fix issue #${{ github.event.issue.number }}"
          body: |
            This pull request was automatically created to fix the calculate_total() function.